name: CD

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository codeu
        uses: actions/checkout@v4

      - name: Simulando code
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
              '**.py'
              README.md

