name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      id: run_tests
      run: |
        python -m unittest discover -s tests

    - name: Send success alert to Discord
      if: success()  # Envia alerta apenas se os testes passarem
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"content\": \"Testes passados com sucesso!!\"}" \
        ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Send failure alert to Discord
      if: failure()  # Envia alerta apenas se os testes falharem
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"content\": \"Testes passados com erro.\"}" \
        ${{ secrets.DISCORD_WEBHOOK_URL }}
